[package]
name = "raft"
version = "0.1.0"
authors = ["Thiago Pontes <github@thiago.me>"]

[dependencies]
rust-crypto = "^0.2"

[dependencies.bencode]
git = "https://github.com/arjantop/rust-bencode"

